version: "3.8"

services:
  postgres:
    build: 
      context: ./database
    cap_add:
      - SYS_NICE
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    env_file: ./.env

  backend:
    depends_on:
      - postgres
    build: 
      context: ./backend
      target: development
    volumes: 
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    restart: "no"
    environment:
      PORT: ${BACKEND_PORT}
      NODE_ENV: development
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    env_file: ./.env

  frontend:
    depends_on:
      - backend
      - postgres
    build:
      context: ./frontend
      target: development
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: "no"
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file: ./.env

volumes:
    postgres:
      driver: local